"""Add is_active column to Tasks table

Revision ID: 30f33ff462aa
Revises: f415ddc75ff7
Create Date: 2023-05-30 10:56:35.943876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f33ff462aa'
down_revision = 'f415ddc75ff7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_active')
    # ### end Alembic commands ###
